### ISSUE TITLE
Web page load to blank and UI suddenly appears

### ISSUE THREAD

**Issue by ApolloZhu** [aroundu403/AroundU#7]
- an description summary of what goes wrong: webpage load finishes before the contents actually loads
- Which platform you are using?: Frontend in a browser
- Which page you see the issue?: main page
- What kinds of issue? Application Crashed? Rendering Error? Functional Issue?: Rendering Error
- Steps to reproduce the bug:
   - What are the list of steps that leads you to issue?
      - Open https://aroundu-403.web.app/#/
   - Is the error repeatable?
      - Yes
- What are you expecting?
   - Either webpage loads entirely when loading finishes, or have some sort of indication that webpage is still loading
- What actually happened?
   - Webpages loads into entirely blank
   - AroundU UI suddenly appears after a few seconds

**Comment by JinghuaWang** [comment]
Hi Apollo,

This is great constructive feedback on useability. We didn't notice this problem since we, as developers, overlooked this problem when we tested it. Having loading hints is indeed really important to the end-user experience.

I have taken a deep dive into this issue. The root cause that is Flutter web app has a slow initial launch time. It takes 2 seconds to fetch all the scripts and a couple of seconds to render when it first loads. The loading time would be under 1 second in the future reloads when the browser has cached files locally. It seems like this is a Flutter cold-start problem.
At the first glance, it seems like this is a problem with Flutter and there is no way to fix it. It is impossible to add a loading widget suggesting Flutter is loading before Flutter actually loads. It becomes a bootstrap problem. Yet, we found a hacky way to address this problem. Adding customer CSS and div to the Flutter generated index.html can display the loading effect before the rest of the Flutter components can response.

Thanks for your feedback and we have found a way to address this user experience issue.
